### ISSUE TITLE
Parsing failing for some reports

### ISSUE THREAD

**Issue by zoc** [modoboa/modoboa-dmarc#3]
Hi,

I see in my logs that the importer is actually failing for some reports, with the following error:
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/modoboa_dmarc/management/commands/import_aggregated_report.py", line 32, in handle
    lib.import_report_from_stdin()
  File "/usr/local/lib/python2.7/dist-packages/modoboa_dmarc/lib.py", line 128, in import_report_from_stdin
    import_report_from_email(content)
  File "/usr/local/lib/python2.7/dist-packages/modoboa_dmarc/lib.py", line 115, in import_report_from_email
    import_archive(fpo)
  File "/usr/local/lib/python2.7/dist-packages/modoboa_dmarc/lib.py", line 102, in import_archive
    import_report(zfile.read(fname))
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/modoboa_dmarc/lib.py", line 95, in import_report
    import_record(record, report)
  File "/usr/local/lib/python2.7/dist-packages/modoboa_dmarc/lib.py", line 47, in import_record
    if record.header_from is None:
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related_descriptors.py", line 179, in __get__
    "%s has no %s." % (self.field.model.__name__, self.field.name)
django.db.models.fields.related_descriptors.RelatedObjectDoesNotExist: Record has no header_from.
```

Edit: OK, I see the problem: One of my domain, let's call it "domain1.com" is having a domain alias "domain2.me". When getting reports for "domain1.com" everything is OK, but when receiving for "domain2.me", parsing fails due to the fact that the domain alias is obsiously not present in admin_domain table...

**Comment by tonioo** [comment]
Thanks for reporting, it should be fixed now.

**Comment by zoc** [comment]
Well, at least it does not fail with an exception anymore, but it still does not import reports for domain aliases, which are considered as not local by the importer.

**Comment by tonioo** [comment]
Indeed, they are not supported atm.
How would you imagine this enhancement ? How would you present the information ?

**Comment by zoc** [comment]
That's a good question :)

Let me think about it...
